# Generated by Django 4.0.5 on 2022-06-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок новости')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка на новость')),
                ('created', models.DateTimeField(verbose_name='Дата и время сохранения новости в БД')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
